---
title: "project2"
author: "Teagan Norrgard, trn8cwf"
date: "10/11/2022"
output: html_document
---

## PRE_ANALYSIS

### SETTING UP, LOADING PACKAGES
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(tidyr)
library(tidyverse)
library(dplyr)
library(data.table)
library(RColorBrewer)
library(gridExtra)
library(grid)

## importing csv
mental <- read.csv("/Users/teagannorrgard/Downloads/new.csv", sep="\t")

```

## PRELIMINARY ANALYSIS {.tabset}

### DATA CLEANING AND EXTRACTION
```{r}
# wanted to change the religion column from numbers to the actual religion for easier plot digestion
# some denomination of christian was represented by several numbers, we grouped them all together as one
# this info was obtained from the codebook
mental$religion[mental$religion == 1] <- "Agnostic"
mental$religion[mental$religion == 2] <- "Atheist"
mental$religion[mental$religion == 3] <- "Buddhist"
mental$religion[mental$religion == 4 | mental$religion == 5 | mental$religion == 6 | mental$religion == 7] <- "Christian"
mental$religion[mental$religion == 8] <- "Hindu"
mental$religion[mental$religion == 9] <- "Jewish"
mental$religion[mental$religion == 10] <- "Muslim"
mental$religion[mental$religion == 11] <- "Sikh"
mental$religion[mental$religion == 12] <- "Other"

# since we are concerned with religion, we omitted any survey responses that did not answer this question. These were entered as 0.
mental <- mental[mental$religion != 0, ]

# next we chose which questions could be an indicator of anxiety or depression, respectively
# we subsetted just the A column for questions we were interested in, since these were the actual answers (E and I were time and order)
anxiety <- mental %>%
  select(c('Q6A', 'Q7A', 'Q8A', 'Q9A', 'Q12A', 'Q19A', 'Q20A', 'Q22A', 'Q27A', 'Q28A', 'Q29A', 'Q33A', 'religion'))

depression <- mental%>%
  select(c('Q3A', 'Q5A', 'Q13A', 'Q16A', 'Q17A', 'Q24A', 'Q31A', 'Q34A', 'Q37A', 'Q38A', 'Q42A', 'religion'))

```

### DATA TRANSFORMATION

(comparing ALL religions)
```{r}

# grouping by religion and then averaging over all questions
# chose to use averages because of the huge number of responses - cant put 40,000 data points into a plot and still be digestable
# there are also no outliers in this data since people could only answer with numbers 1-4
avgAnxiety <- anxiety %>% 
    group_by(religion) %>%
    summarise_all("mean")

avgDepresh <- depression %>% 
    group_by(religion) %>%
    summarise_all("mean")

# notable that q42 had highest overall score for depression - I found it difficult to work up the initiative to do things.
# nothing in the 3s for anxiety, but lots of 1s for q19 - I perspired noticeably (eg, hands sweaty) in the absence of high temperatures or physical exertion.

table(mental$religion)

```

### ANXIETY VISUALIZATIONS
```{r}

## anxiety related statements

## we chose random statements of the preselected ones just for a baseline understanding of our data.
ap1 <- ggplot(avgAnxiety, aes(x=religion, y=Q7A, fill=religion)) + 
  geom_bar(stat = "identity") + 
  coord_cartesian(ylim=c(1.5,2.5)) +
  xlab("Religion") + ylab("I had a feeling of shakiness.")

ap2 <- ggplot(avgAnxiety, aes(x=religion, y=Q8A, fill=religion)) + 
  geom_bar(stat = "identity") + 
  coord_cartesian(ylim=c(2,3)) +
  xlab("Religion") + ylab("I found it difficult to relax.")

ap3 <- ggplot(avgAnxiety, aes(x=religion, y=Q9A, fill=religion)) + 
  geom_bar(stat = "identity") + 
  coord_cartesian(ylim=c(2,3)) +
  xlab("Religion") + ylab("I found myself in situations that made me so anxious I was relieved when they ended.")+
  theme(axis.title.y = element_text(size = 8))

ap4 <- ggplot(avgAnxiety, aes(x=religion, y=Q19A, fill=religion)) + 
  geom_bar(stat = "identity") + 
  coord_cartesian(ylim=c(1.5,2.5)) +
  xlab("Religion") + ylab("I perspired noticeably in the absence of high temperatures or physical exertion.")

ap5 <- ggplot(avgAnxiety, aes(x=religion, y=Q20A, fill=religion)) + 
  geom_bar(stat = "identity") + 
  coord_cartesian(ylim=c(1.5,2.5)) +
  xlab("Religion") + ylab("I felt scared without any good reason.")

ap6 <- ggplot(avgAnxiety, aes(x=religion, y=Q22A, fill=religion)) + 
  geom_bar(stat = "identity") + 
  coord_cartesian(ylim=c(2,3)) +
  xlab("Religion") + ylab("I found it hard to wind down.")

ap7 <- ggplot(avgAnxiety, aes(x=religion, y=Q28A, fill=religion)) + 
  geom_bar(stat = "identity") + 
  coord_cartesian(ylim=c(1.5,2.5)) +
  xlab("Religion") + ylab("I felt I was close to panic.")

ap8 <- ggplot(avgAnxiety, aes(x=religion, y=Q29A, fill=religion)) + 
  geom_bar(stat = "identity") + 
  coord_cartesian(ylim=c(2,3)) +
  xlab("Religion") + ylab("I found it hard to calm down after something upset me.")

# grid.arrange(ap1, ap2, ap3, ap4, ap5, ap6, ap7, ap8, ncol = 4)
```

### DEPRESSION VISUALIZATIONS
```{r}

## depression related statements

## we chose random statements of the preselected ones just for a baseline understanding of our data.
dp1 <- ggplot(avgDepresh, aes(x=religion, y=Q3A, fill=religion)) + 
  geom_bar(stat = "identity") + 
  coord_cartesian(ylim=c(1.5,2.5)) +
  xlab("Religion") + ylab("I couldn't seem to experience any positive feeling at all.")

dp2 <- ggplot(avgDepresh, aes(x=religion, y=Q13A, fill=religion)) + 
  geom_bar(stat = "identity") + 
  coord_cartesian(ylim=c(2,3)) +
  xlab("Religion") + ylab("I felt sad and depressed.")

dp3 <- ggplot(avgDepresh, aes(x=religion, y=Q17A, fill=religion)) + 
  geom_bar(stat = "identity") + 
  coord_cartesian(ylim=c(2,3)) +
  xlab("Religion") + ylab("I felt I wasn't worth much as a person.")

dp4 <- ggplot(avgDepresh, aes(x=religion, y=Q24A, fill=religion)) + 
  geom_bar(stat = "identity") + 
  coord_cartesian(ylim=c(2,3)) +
  xlab("Religion") + ylab("I couldn't seem to get any enjoyment out of the things I did.")

dp5 <- ggplot(avgDepresh, aes(x=religion, y=Q31A, fill=religion)) + 
  geom_bar(stat = "identity") + 
  coord_cartesian(ylim=c(2,3)) +
  xlab("Religion") + ylab("I was unable to become enthusiastic about anything.")

dp6 <- ggplot(avgDepresh, aes(x=religion, y=Q34A, fill=religion)) + 
  geom_bar(stat = "identity") + 
  coord_cartesian(ylim=c(2,3)) +
  xlab("Religion") + ylab("I felt I was pretty worthless.")

dp7 <- ggplot(avgDepresh, aes(x=religion, y=Q37A, fill=religion)) + 
  geom_bar(stat = "identity") + 
  coord_cartesian(ylim=c(2,3)) +
  xlab("Religion") + ylab("I could see nothing in the future to be hopeful about.")

dp8 <- ggplot(avgDepresh, aes(x=religion, y=Q38A, fill=religion)) + 
  geom_bar(stat = "identity") + 
  coord_cartesian(ylim=c(2,3)) +
  xlab("Religion") + ylab("I felt that life was meaningless.")

# grid.arrange(dp1, dp2, dp3, dp4, dp5, dp6, dp7, dp8, ncol=2)
grid.arrange(dp7, dp8)
```


## FORMAL ANALYSIS {.tabset}

### DATA TRANSFORMATION 

(grouping Buddhist/Hindu vs others)
```{r}
avgAnxiety$religion[avgAnxiety$religion == "Agnostic" | avgAnxiety$religion == "Atheist" | 
                      avgAnxiety$religion == "Christian" | avgAnxiety$religion == "Jewish" | 
                      avgAnxiety$religion == "Muslim" | avgAnxiety$religion == "Sikh" | 
                      avgAnxiety$religion == "Other"] <- "Other"
avgAnxiety$religion[avgAnxiety$religion == "Buddhist" | avgAnxiety$religion == "Hindu"] <- "Buddhist/Hindu"

avgDepresh$religion[avgDepresh$religion == "Agnostic" | avgDepresh$religion == "Atheist" | 
                      avgDepresh$religion == "Christian" | avgDepresh$religion == "Jewish" | 
                      avgDepresh$religion == "Muslim" | avgDepresh$religion == "Sikh" | 
                      avgDepresh$religion == "Other"] <- "Other"
avgDepresh$religion[avgDepresh$religion == "Buddhist" | avgDepresh$religion == "Hindu"] <- "Buddhist/Hindu"

avgAnxiety2 <- avgAnxiety %>% 
    group_by(religion) %>%
    summarise_all("mean")

avgDepresh2 <- avgDepresh %>% 
    group_by(religion) %>%
    summarise_all("mean")

## we also narrowed down through research which 4 statements for anxiety and depression we should use to test our hypothesis
## we chose: anxiety - 8, 11, 22, 28, depression - 13, 16, 34, 42
## we used these questions to create a new dataframe in excel which we loaded in next:


anxDF <- read_csv("/Users/teagannorrgard/ds4001/anxietyStatements.csv")
depDF <- read_csv("/Users/teagannorrgard/ds4001/depressionStatements.csv")

```

### DATA VISUALIZATION
```{r}
## we made grouped bar plots for our 4 selected statements for anxiety and depression symptoms

## we chose to put a y range on the plot of 1-4 since those were the numbers participants could rank themselves.

ggplot(anxDF, aes(fill=religion, y=mean, x=statement)) + 
    geom_bar(position="dodge", stat="identity")+ 
  coord_cartesian(ylim=c(1,4)) +
  ggtitle("Anxiety Statements")

ggplot(depDF, aes(fill=religion, y=mean, x=statement)) + 
    geom_bar(position="dodge", stat="identity")+ 
  coord_cartesian(ylim=c(1,4)) +
  ggtitle("Depression Statements")
```

### RUNNING STATISTICAL ANALYSIS
```{r}
## we decided to run a t-test since we are just comparing means of 2 groups
## first thing we need to do is to create vectors of the selected statements. I chose to do this manually due to the small size of vectors being created

BHanxiety <- c(2.455348, 1.780996, 2.256442, 2.093409)
Oanxiety <- c(2.593910, 1.945375, 2.441263, 2.299697)

BHdepression <- c(2.637018, 2.396929, 2.411575, 2.584821)
Odepression <- c(2.813102, 2.680705, 2.639654, 2.846305)

t.test(BHanxiety, Oanxiety, paired=TRUE)

t.test(BHdepression, Odepression, paired=TRUE)

## both p values are low so we can accept our hypothesis that people who identify as Buddhist/Hindu exhibit less symptoms of anxiety and depression.
```


